INSERT INTO MANUFACTURER(code, name)
VALUES (100, 'Audi');
INSERT INTO MANUFACTURER(code, name)
VALUES (101, 'Chevrolet');
INSERT INTO MANUFACTURER(code, name)
VALUES (102, 'Ford');
INSERT INTO MANUFACTURER(code, name)
VALUES (103, 'BMW');
INSERT INTO MANUFACTURER(code, name)
VALUES (104, 'Dodge');
INSERT INTO MANUFACTURER(code, name)
VALUES (105, 'Bentley');